In [15]:
import pandas as pd
import numpy as np

In [96]:
df = pd.read_csv("labelleddata.csv")

In [97]:
df.head()

Unnamed: 0                                           Keywords  \
0           0  india, northern, period, world, southern, dyna...   
1           1  india, northern, period, world, southern, dyna...   
2           2  name, feature, make, olympus, valley, map, new...   
3           3  defeat, india, team, point, tournament, year, ...   
4           4  india, northern, period, world, southern, dyna...   

   Topic_Perc_Contrib  Dominant_Topic  
0              0.8364             5.0  
1              0.3866             5.0  
2              0.6672             2.0  
3              0.4617             1.0  
4              0.8092             5.0

In [98]:
df = df.drop(['Unnamed: 0','Topic_Perc_Contrib'],axis = 1)

In [99]:
df.head()

Keywords  Dominant_Topic
0  india, northern, period, world, southern, dyna...             5.0
1  india, northern, period, world, southern, dyna...             5.0
2  name, feature, make, olympus, valley, map, new...             2.0
3  defeat, india, team, point, tournament, year, ...             1.0
4  india, northern, period, world, southern, dyna...             5.0

In [100]:
df['Dominant_Topic'] = df['Dominant_Topic'].astype(int)


In [101]:
df.head()

Keywords  Dominant_Topic
0  india, northern, period, world, southern, dyna...               5
1  india, northern, period, world, southern, dyna...               5
2  name, feature, make, olympus, valley, map, new...               2
3  defeat, india, team, point, tournament, year, ...               1
4  india, northern, period, world, southern, dyna...               5

In [102]:
df.isnull().sum()

Keywords          0
Dominant_Topic    0
dtype: int64

In [103]:
from sklearn.preprocessing import LabelEncoder
# target_feature = df['Dominant_Topic']
#use encoder and transform
encoder = LabelEncoder()
encoded_values = encoder.fit_transform(df['Keywords'].values)
df['Keywords'] = pd.Series(encoded_values, index=df.index)

In [104]:
df.head()

Keywords  Dominant_Topic
0         2               5
1         2               5
2         5               2
3         0               1
4         2               5

In [24]:
# from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.naive_bayes import MultinomialNB

# cv = CountVectorizer()

# df['Keywords'] = cv.fit_transform(df['Keywords']).toarray()

In [105]:
df.head(10)

Keywords  Dominant_Topic
0         2               5
1         2               5
2         5               2
3         0               1
4         2               5
5         5               2
6         2               5
7         2               5
8         2               5
9         2               5

In [78]:
df = pd.get_dummies(df)

In [106]:
df.head()

Keywords  Dominant_Topic
0         2               5
1         2               5
2         5               2
3         0               1
4         2               5

In [107]:
X = df.loc[:,['Keywords']]

y = df['Dominant_Topic']

In [110]:
#SPLITTING THE DATA
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 47)

In [111]:
from sklearn.neighbors import KNeighborsClassifier
k=KNeighborsClassifier()
k.fit(X_train,y_train)
result=k.predict(X_test)
print(accuracy_score(y_test,result))

1.0


In [112]:
from sklearn.tree import DecisionTreeClassifier
d=DecisionTreeClassifier()
d.fit(X_train,y_train)
y_pred=d.predict(X_test)

print(accuracy_score(y_test,y_pred))

1.0


In [113]:
from sklearn.ensemble import GradientBoostingClassifier
gbc=GradientBoostingClassifier()
gbc.fit(X_train,y_train)
y_pred=gbc.predict(X_test)

print(accuracy_score(y_test,y_pred))

1.0


In [75]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)

In [76]:
print(accuracy_score(y_test,y_pred))

1.0


In [77]:
df.to_csv("final.csv")

In [83]:
# clf = MultinomialNB()
# clf.fit(X_train, y_train)
# y_pred = clf.predict(X_test)

In [84]:
# from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
# cm = confusion_matrix(y_test, y_pred)
# print(cm)
# print(accuracy_score(y_test, y_pred))
# print(classification_report(y_test, y_pred))

[[ 0  0  0  0  0 34]
 [ 0  0  0  0  0 36]
 [ 0  0  0  0  0 23]
 [ 0  0  0  0  0 23]
 [ 0  0  0  0  0 25]
 [ 0  0  0  0  0 44]]
0.23783783783783785
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.00      0.00      0.00        36
           2       0.00      0.00      0.00        23
           3       0.00      0.00      0.00        23
           4       0.00      0.00      0.00        25
           5       0.24      1.00      0.38        44

    accuracy                           0.24       185
   macro avg       0.04      0.17      0.06       185
weighted avg       0.06      0.24      0.09       185



C:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [85]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
clf.fit(X_train,y_train)

RandomForestClassifier()

In [86]:
y_pred=clf.predict(X_test)

In [87]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[34  0  0  0  0  0]
 [ 0 36  0  0  0  0]
 [ 0  0 23  0  0  0]
 [ 0  0  0 23  0  0]
 [ 0  0  0  0 25  0]
 [ 0  0  0  0  0 44]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        34
           1       1.00      1.00      1.00        36
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00        23
           4       1.00      1.00      1.00        25
           5       1.00      1.00      1.00        44

    accuracy                           1.00       185
   macro avg       1.00      1.00      1.00       185
weighted avg       1.00      1.00      1.00       185



In [88]:
import pickle
#Fitting model with trainig data
clf.fit(X, y)

# Saving model to disk
pickle.dump(clf, open('model.pkl','wb'))
